// Mocks generated by Mockito 5.1.0 from annotations
// in my_river_calc/test/screens/calculator/providers/calculator_viewmodel_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_river_calc/repository/calculator_api_impl.dart' as _i2;
import 'package:my_river_calc/utils/calculator_operator.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [CalculatorApiImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculatorApiImpl extends _i1.Mock implements _i2.CalculatorApiImpl {
  MockCalculatorApiImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int?> calculatorComputation(
          int? num1, int? num2, _i4.CalculatorOperator? operator) =>
      (super.noSuchMethod(
          Invocation.method(#calculatorComputation, [num1, num2, operator]),
          returnValue: Future<int?>.value()) as _i3.Future<int?>);
}
